app:
  name: RapidoJS Example API
  version: 0.1.0
  port: 8395
  debug: false
  
database:
  host: localhost
  port: 5432
  name: rapidojs_example
  ssl: false
  
redis:
  host: localhost
  port: 6379
  db: 0
  
jwt:
  expiresIn: 7d
  
logging:
  level: info
  format: json 